/* Fable Theft Auto 5.1 - every word the game shows, in Chinese (the default) and English. The host's simulation puts keys and
   vars on the wire (a `float` is [type, player, key, colour, vars], a `news` line carries a street or a district by its number),
   and each screen reads them in its own language through core/i18n.js (`makeT(STR)`). `{name}` in a string is filled from the
   vars. The canvas HUD upper-cases whatever it draws, so the case here only matters on the DOM cards. Street and district names
   are world data (world.js keeps the English for the shop signs and the building styles); these are how they are said.
   No DOM: test/strings.test.mjs checks the two tables against each other in node. */
const en = {
  title: 'FABLE THEFT AUTO', city: 'LOS PIXELES', 'grab.click': 'CLICK TO PLAY', 'grab.tap': 'TAP TO PLAY', 'resume.click': 'CLICK TO RESUME', 'resume.tap': 'TAP TO RESUME',
  'card.mw': 'MOST WANTED: CARRY THE MARK, HUNT THE MARK', 'card.dm': 'DEATHMATCH: FIRST TO {n} KILLS', 'card.race': 'STREET RACE: {laps}, {guns}', 'card.hit': 'MISSION: THE DOWNTOWN HIT',
  'laps.1': '{n} LAP', 'laps.n': '{n} LAPS', anyGoes: 'ANYTHING GOES', noGuns: 'NO GUNS',
  paused: 'PAUSED', 'paused.online': 'THE CITY KEEPS RUNNING WITHOUT YOU',
  'btn.resume': 'RESUME', 'btn.soundOn': 'SOUND: ON', 'btn.soundOff': 'SOUND: OFF', 'btn.detail': 'DETAIL: {q}', 'q.auto': 'AUTO ({q})', 'q.0': 'HIGH', 'q.1': 'MEDIUM', 'q.2': 'LOW',
  'btn.look': 'LOOK: {l}', 'look.0': 'LOW', 'look.1': 'NORMAL', 'look.2': 'HIGH', 'btn.howto': 'HOW TO PLAY', 'btn.statsOn': 'STATS: ON', 'btn.statsOff': 'STATS: OFF',
  'btn.restart': 'RESTART', 'btn.restartAll': 'RESTART FOR EVERYONE', 'btn.menu': 'MENU', 'btn.lobby': 'BACK TO LOBBY', 'btn.endRound': 'END ROUND', 'btn.leave': 'LEAVE ROOM',
  'btn.rematch': 'REMATCH?', 'btn.rematchOn': 'REMATCH: YES', 'btn.again': 'PLAY AGAIN', wantRematch: '{n} WANT A REMATCH', 'wantRematch.1': '1 WANTS A REMATCH',
  waitHost: 'WAITING FOR THE HOST TO PLAY AGAIN OR RETURN TO THE LOBBY…', waitHud: 'WAITING FOR THE HOST…',
  'over.race': 'RACE OVER', 'over.dm': 'DEATHMATCH OVER', 'over.time': "TIME'S UP", 'over.ended': 'ROUND OVER',
  'sub.race': 'FINAL STANDINGS  ·  FIRST ACROSS THE LINE WINS', 'sub.dm': 'FINAL STANDINGS  ·  MOST KILLS WINS', 'sub.cash': 'FINAL STANDINGS  ·  MOST CASH WINS',
  'sc.finished': 'FINISHED {o}', 'sc.lapcp': 'LAP {lap}/{laps}  ·  CP {cp}/{n}', 'sc.kills': '{n} kills', 'sc.marked': '{t} marked', 'sc.cpu': 'CPU', 'sc.left': 'LEFT',
  'aw.lap': 'FASTEST LAP', 'aw.killer': 'MOST KILLS', 'aw.nemesis': 'NEMESIS', 'aw.victim': 'MOST WASTED', 'aw.fugitive': 'LONGEST CHASE', 'aw.cabbie': 'BEST CABBIE', 'aw.speed': 'SPEED DEMON', 'aw.driver': 'SAFEST DRIVER', 'aw.loot': 'BIGGEST LOOTER',
  'awv.kills.1': '{n} KILL', 'awv.kills': '{n} KILLS', 'awv.nemesis': 'WASTED {name} {n} TIMES', 'awv.victim': '{n} DEATHS', 'awv.fugitive': '{t} ON THE RUN', 'awv.cabbie': '{n} FARES IN A ROW',
  'awv.speed': '{n} KM/H', 'awv.driver.0': 'NO CRASHES IN {km} KM', 'awv.driver.1': '{n} CRASH IN {km} KM', 'awv.driver': '{n} CRASHES IN {km} KM', 'awv.loot': '${n} PICKED UP',
  controls: [['WASD', 'move / drive'], ['MOUSE', 'look / aim'], ['CLICK', 'shoot (from the passenger seat too)'], ['1-5 / Q', 'switch weapon (or the wheel)'], ['R', 'reload'], ['F', "enter / exit a car, ride along in a friend's, turn yourself in"],
    ['SHIFT', 'sprint'], ['SPACE', 'jump / handbrake'], ['TAB', 'scoreboard (hold)'], ['M', 'sound on / off'], ['F3 / I', 'stats panel'], ['L', 'graphics detail'], ['ESC', 'pause']],
  controlsTouch: [['LEFT SIDE', 'drag to move or drive · push all the way to run'], ['RIGHT SIDE', 'drag to look and aim'], ['FIRE', 'hold to shoot (from the passenger seat too) · drag on it to aim while shooting'], ['JUMP', 'jump on foot, handbrake in a car'],
    ['USE', "enter or exit a car, ride along in a friend's, turn yourself in"], ['WEAPON', 'next weapon · RELOAD reloads'], ['☰', 'pause, sound, detail, look sensitivity'], ['SCORES', 'the scoreboard']],
  rotate: 'ROTATE YOUR DEVICE', 'rotate.sub': 'FABLE THEFT AUTO PLAYS IN LANDSCAPE', dragMove: 'DRAG HERE TO MOVE', dragLook: 'DRAG HERE TO LOOK',
  't.fire': 'FIRE', 't.jump': 'JUMP', 't.use': 'USE', 't.reload': 'RELOAD', 't.handbrake': 'HANDBRAKE', 't.exit': 'EXIT', 't.jack': 'JACK', 't.enter': 'ENTER', 't.getin': 'GET IN', 't.turnin': 'TURN IN', 't.board': 'SCORES',
  'w.pistol': 'PISTOL', 'w.shotgun': 'SHOTGUN', 'w.smg': 'SMG', 'w.sniper': 'SNIPER', 'w.rpg': 'ROCKET',
  'pk.pistol': 'PISTOL', 'pk.shotgun': 'SHOTGUN', 'pk.smg': 'SMG', 'pk.sniper': 'SNIPER RIFLE', 'pk.rpg': 'ROCKET LAUNCHER',
  'cause.pistol': 'PISTOL', 'cause.shotgun': 'SHOTGUN', 'cause.smg': 'SMG', 'cause.sniper': 'SNIPER RIFLE', 'cause.rpg': 'ROCKET', 'cause.runover': 'RUN OVER', 'cause.explosion': 'BLOWN UP',
  'cause.cop': 'SHOT BY THE LPPD', 'cause.guard': 'SHOT BY THE BODYGUARDS', 'cause.swat': 'SHOT BY SWAT', 'cause.fence': 'LEFT THE ARENA', 'cause.crash': 'CAME OFF THE BIKE',
  'kv.runover': 'RAN OVER', 'kv.explosion': 'BLEW UP', 'kv.crash': 'KNOCKED OFF THE BIKE', 'kv.wasted': 'WASTED',
  'died.cop': 'SHOT BY THE LPPD', 'died.swat': 'SHOT BY SWAT', 'died.guard': 'SHOT BY THE BODYGUARDS', 'died.runover': 'RUN OVER', 'died.explosion': 'BLOWN UP', 'died.crash': 'CAME OFF THE BIKE', 'died.fence': 'LEFT THE ARENA', 'died.wasted': 'WASTED',
  'job.taxi': 'TAXI DRIVER', 'job.ambulance': 'PARAMEDIC', 'who.fare': 'FARE', 'who.patient': 'PATIENT', 'ev.truck': 'ARMORED TRUCK', 'ev.airdrop': 'AIRDROP', 'ev.event': 'EVENT',
  'hint.1': 'F  EXIT CAR      SPACE  HANDBRAKE', 'hint.2': 'F  JACK CAR', 'hint.3': 'F  ENTER CAR', 'hint.4': 'STOP IN THE BAY TO RESPRAY   $100 A STAR', 'hint.5': 'F  TURN YOURSELF IN   $100 A STAR', 'hint.6': 'F  GET OUT', 'hint.7': 'F  GET IN',
  'hint.t5': 'TURN YOURSELF IN   $100 A STAR',
  'obj.intro': 'Get to Diamond Plaza, downtown.', 'obj.goto': 'Get to Diamond Plaza, downtown.', 'obj.hit': "Whack Vinny 'Snitch' Voxel. Watch the bodyguards.", 'obj.passed': 'Mission passed. Lose the cops.',
  'obj.escape': "Lose the wanted level: hide out, find a bribe, hit the Pay 'n' Spray or turn yourself in.", 'obj.done': 'Free roam. Cause chaos in Los Pixeles.',
  'brief.hit': "Vinny 'Snitch' Voxel sold out the crew to the LPPD. He's hiding at Diamond Plaza downtown with hired muscle. Make him disappear.",
  'brief.mw': 'Someone in Los Pixeles carries the mark. It pays ${cash} a second to whoever holds it, and whoever kills them takes it, plus a ${bounty} bounty.',
  'brief.dm': 'Everyone is fair game and nobody gets a star for it, inside the red fence. Leave it and you have {t} seconds to get back. First to {cap} kills wins, or the most when the clock runs out. {guns}',
  'brief.dm.guns': 'Guns, cars, whatever works.', 'brief.dm.noguns': 'No guns: cars and your fists.',
  'brief.race': '{laps} through the checkpoints and back across the line. {guns} The first one home gives the rest {t} seconds.',
  'brief.race.guns': 'Anything goes: guns, traffic, cops.', 'brief.race.noguns': 'No guns: traffic, cops and your bumper.',
  'n.gun': 'FOUND A {w}', 'n.stars': 'IS WANTED  *****', 'n.escape': 'ESCAPED A 5-STAR CHASE  +${n}', 'n.busted': 'WENT TO THE PRECINCT', 'n.truckBy': 'BLEW THE TRUCK OPEN ON {st}', 'n.truck': 'THE ARMORED TRUCK IS OPEN ON {st}',
  'n.drop': 'AIRDROP DOWN IN {d}', 'n.streak': '{n} FARES IN A ROW', 'n.left': 'LEFT THE CITY', 'n.passed': 'WHACKED THE SNITCH  +$5000', 'n.mark': 'IS THE MOST WANTED', 'n.finish': 'FINISHED {o}', 'f.leftCity': '{name} LEFT THE CITY',
  'p.cash': '+${n}', 'p.ammo': 'AMMO', 'p.bribe': 'BRIBE ACCEPTED  -1 STAR', 'p.bribe0': 'BRIBE ACCEPTED  YOU LOST THE COPS', 'p.gun': '{w}  {n} ROUNDS', 'p.health': '+HEALTH',
  'm.start': 'YOU ARE THE MOST WANTED. STAY ALIVE.', 'm.took': 'YOU TOOK THE MARK. STAY ALIVE.', 'm.other': '{name} IS THE MOST WANTED',
  'we.truck': 'ARMORED TRUCK ON {st}  ·  BLOW IT OPEN', 'we.airdrop': 'AIRDROP INCOMING  ·  {d}',
  'cp.final': 'FINAL LAP', 'cp.lap': 'LAP {n} OF {laps}', 'cp.cp': 'CHECKPOINT {k} OF {n}',
  'fin.you': 'YOU FINISHED {o}', 'fin.other': '{name} FINISHED {o}', 'fin.ends': 'THE RACE ENDS IN {n} SECONDS',
  // what the host's simulation says to one player (or the room) as a float: the key and its vars ride the wire
  'f.thrown': 'THROWN OFF', 'f.wasted': 'WASTED {name}  +$100', 'f.bounty': 'BOUNTY  +${n}', 'f.course': 'BACK ON THE COURSE', 'f.arena': 'BACK IN THE ARENA', 'f.bill': 'HOSPITAL BILL -$300',
  'f.escape': '5-STAR ESCAPE  +${n}', 'f.sprayCost': 'THE RESPRAY COSTS ${n}', 'f.sprayed': 'RESPRAYED  -${n}', 'f.busted': 'BUSTED  -${n}', 'f.confiscated': 'SPARE AMMO CONFISCATED',
  'f.carjack': 'CARJACKING', 'f.roadblock': 'ROADBLOCK AHEAD', 'f.heat': 'LOSING THE HEAT', 'f.lost': 'YOU LOST THE COPS', 'f.run': "VINNY'S MAKING A RUN FOR IT!", 'f.there': 'THERE HE IS. TAKE HIM OUT.',
  'f.getaway': 'CLEAN GETAWAY', 'f.truckOpen': 'THE ARMORED TRUCK IS OPEN. GRAB THE CASH!', 'f.fareWait': '{who} WAITING ON {st}', 'f.fareRan': 'THE FARE RAN OFF', 'f.fareGone': 'YOUR FARE IS GONE',
  'f.patientDied': "THE PATIENT DIDN'T MAKE IT", 'f.otherCab': 'THE FARE TOOK ANOTHER CAB', 'f.tooLate': 'TOO LATE FOR THE PATIENT', 'f.tooSlow': 'TOO SLOW. THE {who} GOT OUT',
  'f.taxiJob': 'TAXI JOB  ·  FARES PAY BY THE METRE', 'f.ambJob': 'PARAMEDIC  ·  GET THE PATIENTS TO THE HOSPITAL', 'f.takeFare': 'TAKE THE FARE TO {st}  ${n}', 'f.takePatient': 'GET THE PATIENT TO THE HOSPITAL  ${n}',
  'f.farePaid': 'FARE PAID  +${n}', 'f.delivered': 'PATIENT DELIVERED  +${n}', 'f.tip': '(TIP ${n})', 'f.streak': '({k} IN A ROW +${n})', 'f.outArena': 'OUT OF THE ARENA  ·  GET BACK',
  'q.float': '{q} DETAIL', 'q.lowFps': 'LOW FRAME RATE: {q} DETAIL', 'fb.mw': 'MOST WANTED NEEDS TWO PLAYERS: SANDBOX INSTEAD', 'fb.dm': 'A DEATHMATCH NEEDS TWO PLAYERS (OR CPU PLAYERS ON): SANDBOX INSTEAD',
  // the HUD
  killcam: 'KILLCAM', 'killcam.eyes': 'THROUGH THE EYES OF {name}', reloading: 'RELOAD', kills: 'KILLS {n}', round: 'ROUND {t}', finished: 'FINISHED', raceEnds: 'RACE ENDS {t}',
  'g.then': 'THEN {turn}  ·  {st}', 'g.thenStraight': 'THEN STRAIGHT ON', 'g.straight': 'STRAIGHT ON', 'turn.LEFT': 'LEFT', 'turn.RIGHT': 'RIGHT', 'turn.U-TURN': 'U-TURN', 'turn.STRAIGHT': 'STRAIGHT', 'g.dist': '{label}  {n} M',
  goal: 'GOAL', finish: 'FINISH', cpn: 'CP {n}', dropoff: 'DROP OFF', target: 'TARGET', markTag: 'MARK {name}', distTag: '{label} {n}M',
  'o.grid': 'On the grid. Wait for the green.', 'o.finished': 'You finished {o}.', 'o.rest': 'The rest have {n} s.', 'o.cp': 'Checkpoint {k} of {n}, {st}.  {o} of {m}.', 'o.line': 'Back across the line, {st}.  {o} of {m}.',
  'o.jobWait': 'A {who} is on the way.', 'o.jobPick': 'Pick up the {who} on {st}.', 'o.jobDrop': 'Take the {who} to {st}.', 'o.jobHosp': 'Take the {who} to the hospital.', 'o.inRow': '{n} in a row',
  'o.dm': '{n} of {cap} kills.  {lead}', 'o.dmNone': 'Nobody has scored yet.', 'o.dmYou': 'You lead.', 'o.dmLead': '{name} leads with {n}.',
  'o.mwDraw': 'The mark is drawn in a moment. Find a car.', 'o.mwYou': 'You are the mark. Stay alive: +${n} a second.', 'o.mwHunt': 'Hunt {name}. The kill pays ${n} and the mark.',
  'h.race': 'STREET RACE', 'h.dm': 'DEATHMATCH', 'h.mw': 'MOST WANTED', 'h.hit': 'THE DOWNTOWN HIT',
  onGrid: 'ON THE GRID', 'grid.sub': '{laps}  ·  {n} CHECKPOINTS  ·  {guns}', backIn: 'GET BACK IN THE ARENA', takingDmg: 'YOU ARE TAKING DAMAGE', getBack: 'GET BACK', go: 'GO!', acrossFirst: 'FIRST ACROSS THE LINE', across: 'ACROSS THE LINE',
  'we.dropDown': 'AIRDROP DOWN  ·  {t}', 'we.dropIn': 'AIRDROP LANDS IN {n}', 'we.open': 'TRUCK OPEN  ·  {t}', 'we.truckT': 'ARMORED TRUCK  ·  {t}',
  'intro.dm': 'FIRST TO {n} KILLS. NO STARS FOR IT.', 'intro.mw': 'CARRY THE MARK. HUNT THE MARK.', 'intro.hit': 'WHACK THE SNITCH', wantedLvl: 'WANTED LEVEL {s}',
  wasted: 'WASTED', passed: 'MISSION PASSED', respect: 'RESPECT +', 'd.runBy': 'RUN OVER BY {name}', 'd.blownBy': 'BLOWN UP BY {name}', 'd.by': 'WASTED BY {name}', 'd.dist': '{n} M',
  'net.host': 'HOST', 'net.lag': 'LAG {n} MS  HOST {f} FPS', protected: 'SPAWN PROTECTION',
  board: 'SCOREBOARD', 'b.player': 'PLAYER', 'b.cash': 'CASH', 'b.kills': 'KILLS', 'b.deaths': 'DEATHS', 'b.wanted': 'WANTED', 'b.mark': 'MARKED', 'b.place': 'PLACE', 'b.dead': 'DEAD', 'b.hint': 'HOLD TAB', 'b.hintTouch': 'TAP SCORES TO CLOSE',
  ord: '#{n}',
  // the city: world.js's street and district names, as they are said
  avenues: ['Notch Ave', 'Mojang Blvd', 'Creeper St', 'Ender Ave', 'Obsidian Way', 'Redstone Rd', 'Diamond Ave', 'Emerald Blvd', 'Nether Ave', 'Cobble St', 'Spruce Ave', 'Bedrock Blvd', 'Slime Ln'],
  streets: ['Glowstone St', 'Pickaxe St', 'Lava Ln', 'Shulker St', 'Piston Pkwy', 'Quartz St', 'Voxel Blvd', 'Torch St', 'Anvil St', 'Furnace St', 'Lantern St', 'Kelp St', 'Ocean Dr'],
  'street.cross': '{a} & {b}', 'street.boardwalk': 'Boardwalk', 'street.dirt': 'Dirt road',
  districts: ['CRAFTON HILLS', 'REDSTONE INDUSTRIAL', 'LITTLE CUBO', 'DOWNTOWN', 'PIXEL HEIGHTS', 'VOXEL BEACH', 'PACIFIC OF PIXELS', 'VOXEL BEACH BOARDWALK', 'THE OUTSKIRTS'],
};

const zh = {
  title: '寓言盗车手', city: '像素圣城', 'grab.click': '点击开始', 'grab.tap': '轻触开始', 'resume.click': '点击继续', 'resume.tap': '轻触继续',
  'card.mw': '头号通缉:背上标记,追杀标记', 'card.dm': '死斗:先拿 {n} 杀者胜', 'card.race': '街头赛车:{laps},{guns}', 'card.hit': '任务:市中心刺杀',
  'laps.1': '{n} 圈', 'laps.n': '{n} 圈', anyGoes: '不择手段', noGuns: '禁枪',
  paused: '暂停', 'paused.online': '城市可不会等你',
  'btn.resume': '继续', 'btn.soundOn': '声音:开', 'btn.soundOff': '声音:关', 'btn.detail': '画质:{q}', 'q.auto': '自动({q})', 'q.0': '高', 'q.1': '中', 'q.2': '低',
  'btn.look': '视角灵敏度:{l}', 'look.0': '低', 'look.1': '中', 'look.2': '高', 'btn.howto': '操作说明', 'btn.statsOn': '统计:开', 'btn.statsOff': '统计:关',
  'btn.restart': '重新开始', 'btn.restartAll': '全员重开', 'btn.menu': '主菜单', 'btn.lobby': '回到大厅', 'btn.endRound': '结束本局', 'btn.leave': '离开房间',
  'btn.rematch': '再来一局?', 'btn.rematchOn': '再来一局:要!', 'btn.again': '再来一局', wantRematch: '{n} 人想再来一局', 'wantRematch.1': '1 人想再来一局',
  waitHost: '等房主开下一局,或者回大厅…', waitHud: '等待房主…',
  'over.race': '比赛结束', 'over.dm': '死斗结束', 'over.time': '时间到', 'over.ended': '本局结束',
  'sub.race': '最终排名 · 先冲线者胜', 'sub.dm': '最终排名 · 击杀最多者胜', 'sub.cash': '最终排名 · 钱最多者胜',
  'sc.finished': '{o}完赛', 'sc.lapcp': '第 {lap}/{laps} 圈 · 检查点 {cp}/{n}', 'sc.kills': '{n} 杀', 'sc.marked': '背标 {t}', 'sc.cpu': '电脑', 'sc.left': '已离开',
  'aw.lap': '最快单圈', 'aw.killer': '击杀王', 'aw.nemesis': '宿敌', 'aw.victim': '最惨的人', 'aw.fugitive': '最长追逐', 'aw.cabbie': '金牌司机', 'aw.speed': '速度狂魔', 'aw.driver': '最稳车手', 'aw.loot': '搜刮王',
  'awv.kills.1': '{n} 杀', 'awv.kills': '{n} 杀', 'awv.nemesis': '干掉 {name} {n} 次', 'awv.victim': '死了 {n} 次', 'awv.fugitive': '亡命 {t}', 'awv.cabbie': '连送 {n} 单',
  'awv.speed': '时速 {n} 公里', 'awv.driver.0': '{km} 公里零事故', 'awv.driver.1': '{km} 公里只撞了 {n} 次', 'awv.driver': '{km} 公里撞了 {n} 次', 'awv.loot': '捡了 ${n}',
  controls: [['WASD', '走路 / 开车'], ['鼠标', '转视角 / 瞄准'], ['左键', '开枪(坐副驾也能打)'], ['1-5 / Q', '换枪(滚轮也行)'], ['R', '换弹'], ['F', '上下车、搭朋友的车、去警局自首'],
    ['SHIFT', '冲刺'], ['空格', '跳 / 手刹'], ['TAB', '按住看排名'], ['M', '声音开关'], ['F3 / I', '统计面板'], ['L', '画质'], ['ESC', '暂停']],
  controlsTouch: [['左半屏', '拖动走路或开车 · 推到底就跑'], ['右半屏', '拖动转视角、瞄准'], ['开火', '按住射击(坐副驾也能打) · 按住拖动边打边瞄'], ['跳', '步行时跳,开车时手刹'],
    ['互动', '上下车、搭朋友的车、去警局自首'], ['武器', '换下一把 · 换弹键装弹'], ['☰', '暂停、声音、画质、灵敏度'], ['排名', '排行榜']],
  rotate: '请把设备横过来', 'rotate.sub': '寓言盗车手要横屏玩', dragMove: '拖动这里走路', dragLook: '拖动这里转视角',
  't.fire': '开火', 't.jump': '跳', 't.use': '互动', 't.reload': '换弹', 't.handbrake': '手刹', 't.exit': '下车', 't.jack': '抢车', 't.enter': '上车', 't.getin': '搭车', 't.turnin': '自首', 't.board': '排名',
  'w.pistol': '手枪', 'w.shotgun': '霰弹枪', 'w.smg': '冲锋枪', 'w.sniper': '狙击枪', 'w.rpg': '火箭筒',
  'pk.pistol': '手枪', 'pk.shotgun': '霰弹枪', 'pk.smg': '冲锋枪', 'pk.sniper': '狙击步枪', 'pk.rpg': '火箭筒',
  'cause.pistol': '手枪', 'cause.shotgun': '霰弹枪', 'cause.smg': '冲锋枪', 'cause.sniper': '狙击步枪', 'cause.rpg': '火箭弹', 'cause.runover': '被车撞', 'cause.explosion': '被炸',
  'cause.cop': '被警察击毙', 'cause.guard': '被保镖击毙', 'cause.swat': '被特警击毙', 'cause.fence': '离开了竞技场', 'cause.crash': '摔下了摩托',
  'kv.runover': '碾过', 'kv.explosion': '炸飞', 'kv.crash': '撞下摩托', 'kv.wasted': '干掉',
  'died.cop': '被警察击毙', 'died.swat': '被特警击毙', 'died.guard': '被保镖击毙', 'died.runover': '被车撞死', 'died.explosion': '被炸死', 'died.crash': '摔下了摩托', 'died.fence': '死在竞技场外', 'died.wasted': '挂了',
  'job.taxi': '出租车司机', 'job.ambulance': '急救员', 'who.fare': '乘客', 'who.patient': '病人', 'ev.truck': '运钞车', 'ev.airdrop': '空投', 'ev.event': '事件',
  'hint.1': 'F 下车      空格 手刹', 'hint.2': 'F 抢车', 'hint.3': 'F 上车', 'hint.4': '停进车位就能喷漆  每星 $100', 'hint.5': 'F 自首  每星 $100', 'hint.6': 'F 下车', 'hint.7': 'F 搭车',
  'hint.t5': '自首  每星 $100',
  'obj.intro': '去市中心的钻石广场。', 'obj.goto': '去市中心的钻石广场。', 'obj.hit': '干掉"告密者"文尼·沃克索。小心他的保镖。', 'obj.passed': '任务完成。甩掉警察。',
  'obj.escape': '消掉通缉:躲起来、找贿赂、去喷漆店,或者去警局自首。', 'obj.done': '自由活动。把像素圣城搅个天翻地覆。',
  'brief.hit': '"告密者"文尼·沃克索把兄弟们卖给了像素警局。他带着打手躲在市中心的钻石广场。让他人间蒸发。',
  'brief.mw': '像素圣城里有人背着标记。背着它每秒进账 ${cash};谁干掉背标的人,标记就归谁,外加 ${bounty} 赏金。',
  'brief.dm': '红色围栏里人人都是猎物,杀人也不涨通缉。出了围栏,你只有 {t} 秒回来。先拿 {cap} 杀者胜,时间到了就看谁杀得多。{guns}',
  'brief.dm.guns': '枪、车,怎么顺手怎么来。', 'brief.dm.noguns': '禁枪:只有车和拳头。',
  'brief.race': '{laps},依次穿过检查点,再冲回起点线。{guns}第一个冲线后,其他人只剩 {t} 秒。',
  'brief.race.guns': '不择手段:枪、车流、警察都算。', 'brief.race.noguns': '禁枪:车流、警察和你的保险杠。',
  'n.gun': '捡到了{w}', 'n.stars': '被五星通缉 *****', 'n.escape': '甩掉了五星追捕 +${n}', 'n.busted': '去警局自首了', 'n.truckBy': '在{st}炸开了运钞车', 'n.truck': '运钞车在{st}被炸开了',
  'n.drop': '空投落在{d}', 'n.streak': '连送 {n} 单', 'n.left': '离开了城市', 'n.passed': '干掉了告密者 +$5000', 'n.mark': '成了头号通缉犯', 'n.finish': '{o}完赛', 'f.leftCity': '{name} 离开了城市',
  'p.cash': '+${n}', 'p.ammo': '弹药', 'p.bribe': '贿赂成功 -1 星', 'p.bribe0': '贿赂成功 甩掉了警察', 'p.gun': '{w} {n} 发', 'p.health': '+生命',
  'm.start': '你是头号通缉犯。活下去。', 'm.took': '标记到手。活下去。', 'm.other': '{name} 成了头号通缉犯',
  'we.truck': '运钞车出现在{st} · 炸开它', 'we.airdrop': '空投来袭 · {d}',
  'cp.final': '最后一圈', 'cp.lap': '第 {n}/{laps} 圈', 'cp.cp': '检查点 {k}/{n}',
  'fin.you': '你{o}完赛', 'fin.other': '{name} {o}完赛', 'fin.ends': '比赛 {n} 秒后结束',
  'f.thrown': '被甩下车了', 'f.wasted': '干掉 {name} +$100', 'f.bounty': '赏金 +${n}', 'f.course': '回到赛道', 'f.arena': '回到竞技场', 'f.bill': '医药费 -$300',
  'f.escape': '五星逃脱 +${n}', 'f.sprayCost': '喷漆要 ${n}', 'f.sprayed': '喷漆完成 -${n}', 'f.busted': '被捕 -${n}', 'f.confiscated': '备用弹药被没收',
  'f.carjack': '抢车', 'f.roadblock': '前方有路障', 'f.heat': '通缉在降温', 'f.lost': '甩掉警察了', 'f.run': '文尼要跑了!', 'f.there': '就是他。干掉他。',
  'f.getaway': '全身而退', 'f.truckOpen': '运钞车开了,快抢钱!', 'f.fareWait': '{who}在{st}等你', 'f.fareRan': '乘客跑了', 'f.fareGone': '乘客没了',
  'f.patientDied': '病人没救过来', 'f.otherCab': '乘客打了别的车', 'f.tooLate': '病人等不及了', 'f.tooSlow': '太慢了,{who}下车走了',
  'f.taxiJob': '出租车活儿 · 按米计价', 'f.ambJob': '急救员 · 把病人送到医院', 'f.takeFare': '把乘客送到{st} ${n}', 'f.takePatient': '把病人送到医院 ${n}',
  'f.farePaid': '车费到手 +${n}', 'f.delivered': '病人送到 +${n}', 'f.tip': '(小费 ${n})', 'f.streak': '(连送 {k} 单 +${n})', 'f.outArena': '出了竞技场 · 快回去',
  'q.float': '画质:{q}', 'q.lowFps': '帧率太低:画质降为{q}', 'fb.mw': '头号通缉至少要两人:改玩沙盒', 'fb.dm': '死斗至少要两人(或打开电脑补位):改玩沙盒',
  killcam: '击杀回放', 'killcam.eyes': '{name} 的视角', reloading: '换弹中', kills: '击杀 {n}', round: '剩余 {t}', finished: '已完赛', raceEnds: '比赛结束倒计时 {t}',
  'g.then': '然后{turn} · {st}', 'g.thenStraight': '然后直行', 'g.straight': '直行', 'turn.LEFT': '左转', 'turn.RIGHT': '右转', 'turn.U-TURN': '掉头', 'turn.STRAIGHT': '直行', 'g.dist': '{label} {n} 米',
  goal: '目标', finish: '终点', cpn: '检查点 {n}', dropoff: '下客点', target: '目标', markTag: '标记 {name}', distTag: '{label} {n}米',
  'o.grid': '在发车格上。等绿灯。', 'o.finished': '你{o}完赛。', 'o.rest': '其他人还有 {n} 秒。', 'o.cp': '检查点 {k}/{n},{st}。{o},共 {m} 人。', 'o.line': '冲回起点线,{st}。{o},共 {m} 人。',
  'o.jobWait': '{who}马上就来。', 'o.jobPick': '去{st}接{who}。', 'o.jobDrop': '把{who}送到{st}。', 'o.jobHosp': '把{who}送到医院。', 'o.inRow': '连送 {n} 单',
  'o.dm': '{n}/{cap} 杀。{lead}', 'o.dmNone': '还没人得分。', 'o.dmYou': '你领先。', 'o.dmLead': '{name} 以 {n} 杀领先。',
  'o.mwDraw': '马上就要抽出标记。先找辆车。', 'o.mwYou': '你就是标记。活下去:每秒 +${n}。', 'o.mwHunt': '追杀 {name}。击杀赏 ${n},标记也归你。',
  'h.race': '街头赛车', 'h.dm': '死斗', 'h.mw': '头号通缉', 'h.hit': '市中心刺杀',
  onGrid: '准备发车', 'grid.sub': '{laps} · {n} 个检查点 · {guns}', backIn: '回到竞技场', takingDmg: '你在掉血', getBack: '快回去', go: '冲!', acrossFirst: '第一个冲线', across: '冲线',
  'we.dropDown': '空投已落地 · {t}', 'we.dropIn': '空投 {n} 秒后落地', 'we.open': '运钞车已炸开 · {t}', 'we.truckT': '运钞车 · {t}',
  'intro.dm': '先拿 {n} 杀。杀人不涨通缉。', 'intro.mw': '背上标记。追杀标记。', 'intro.hit': '干掉告密者', wantedLvl: '通缉等级 {s}',
  wasted: '你挂了', passed: '任务完成', respect: '声望 +', 'd.runBy': '被 {name} 撞死', 'd.blownBy': '被 {name} 炸死', 'd.by': '被 {name} 干掉', 'd.dist': '{n} 米',
  'net.host': '房主', 'net.lag': '延迟 {n} 毫秒  房主 {f} 帧', protected: '出生保护',
  board: '排行榜', 'b.player': '玩家', 'b.cash': '现金', 'b.kills': '击杀', 'b.deaths': '死亡', 'b.wanted': '通缉', 'b.mark': '背标', 'b.place': '名次', 'b.dead': '阵亡', 'b.hint': '按住 TAB', 'b.hintTouch': '再点排名关闭',
  ord: '第{n}名',
  avenues: ['诺奇大道', '魔赞林荫道', '苦力怕街', '末影大道', '黑曜石路', '红石路', '钻石大道', '绿宝石林荫道', '下界大道', '圆石街', '云杉大道', '基岩林荫道', '史莱姆巷'],
  streets: ['萤石街', '镐子街', '岩浆巷', '潜影贝街', '活塞公园路', '石英街', '体素林荫道', '火把街', '铁砧街', '熔炉街', '灯笼街', '海带街', '海洋大道'],
  'street.cross': '{a}与{b}路口', 'street.boardwalk': '海滨栈道', 'street.dirt': '土路',
  districts: ['克拉夫顿山', '红石工业区', '小方块城', '市中心', '像素高地', '体素海滩', '像素太平洋', '体素海滩栈道', '城郊'],
};

export const STR = { zh, en };
